server:
  port: 80

DB_HOST: ${DB_HOST}
DATABASE_NAME: ${DATABASE_NAME}
READ_REPLICA_DATABASE_NAME: ${READ_REPLICA_DATABASE_NAME}
DATABASE_USERNAME: "sovereignrag"
DATABASE_PASSWORD: "RespectTheHangover"